---
- name: Install and configure Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt package cache
      yum:
        update_cache: yes

    - name: Install Nginx
      yum:
        name: nginx
        state: latest

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

