---
- name: Ping
  import_playbook: 00-ping.yml

- name: Update
  import_playbook:  01-upgrade.yml

- name: Install Nginx
  import_playbook:  02-install-web-server.yml

- name: Copy html file 
  import_playbook:  03-copy-index-html.yml

- name: Provisioning
  import_playbook:  04-provisioning.yml
